# Generated by Django 5.1.7 on 2025-11-24 05:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('professional_id', models.AutoField(primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=200)),
                ('bio', models.TextField()),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('total_reviews', models.IntegerField(default=0)),
                ('completed_jobs', models.IntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('availability_notes', models.TextField(blank=True, null=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('service_radius_km', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'professionals',
            },
        ),
        migrations.CreateModel(
            name='ProfessionalDocument',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('license', 'License'), ('certification', 'Certification'), ('insurance', 'Insurance'), ('id_card', 'ID Card')], max_length=20)),
                ('document_name', models.CharField(max_length=200)),
                ('document_uri', models.CharField(max_length=500)),
                ('is_verified', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verified_by_admin_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'professional_documents',
            },
        ),
        migrations.CreateModel(
            name='ProfessionalService',
            fields=[
                ('prof_service_id', models.AutoField(primary_key=True, serialize=False)),
                ('custom_price_range', models.CharField(blank=True, max_length=100, null=True)),
                ('service_notes', models.TextField(blank=True, null=True)),
                ('estimated_duration_minutes', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'professional_services',
            },
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('hours_id', models.AutoField(primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'working_hours',
            },
        ),
    ]
