# Generated by Django 5.1.7 on 2025-10-05 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professionals', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='professionaldocument',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professionals.professional'),
        ),
        migrations.AddField(
            model_name='professionalservice',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professionals.professional'),
        ),
        migrations.AddField(
            model_name='professionalservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service'),
        ),
        migrations.AddField(
            model_name='workinghours',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professionals.professional'),
        ),
    ]
