# Generated by Django 5.1.7 on 2025-12-12 15:32

from django.db import migrations
from django.db.models import Avg

def recalculate_all_ratings(apps, schema_editor):
    """Recalculate ratings for all professionals based on existing reviews"""
    Professional = apps.get_model('professionals', 'Professional')
    Review = apps.get_model('reviews', 'Review')
    
    professionals_updated = 0
    
    for professional in Professional.objects.all():
        reviews = Review.objects.filter(
            booking__quote__professional=professional,
            is_visible=True
        )
        
        avg_rating = reviews.aggregate(Avg('rating'))['rating__avg']
        professional.rating = avg_rating or 0
        professional.total_reviews = reviews.count()
        professional.save(update_fields=['rating', 'total_reviews'])
        
        professionals_updated += 1
    
    print(f"Updated ratings for {professionals_updated} professionals")

class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
        ('professionals', '0002_initial'),
        ('quotes', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(recalculate_all_ratings),
    ]
