# Generated by Django 5.1.7 on 2025-12-12 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0002_initial'),
        ('requests', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='professionals',
            field=models.ManyToManyField(blank=True, related_name='potential_service_requests', to='professionals.professional'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='professional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_service_requests', to='professionals.professional'),
        ),
    ]
