# Generated by Django 5.1.7 on 2025-10-29 18:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestmedia',
            name='media_uri',
        ),
        migrations.AddField(
            model_name='requestmedia',
            name='media',
            field=models.FileField(default=django.utils.timezone.now, upload_to='request_media/'),
            preserve_default=False,
        ),
    ]
