# Generated by Django 5.1.7 on 2025-10-31 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0002_initial'),
        ('requests', '0003_remove_requestmedia_media_uri_requestmedia_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='professional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to='professionals.professional'),
        ),
    ]
