# Generated by Django 5.1.7 on 2025-10-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('notification_type', models.CharField(choices=[('request', 'Request'), ('quote', 'Quote'), ('booking', 'Booking'), ('payment', 'Payment'), ('system', 'System')], max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('related_entity', models.CharField(blank=True, choices=[('service_request', 'Service Request'), ('booking', 'Booking'), ('payment', 'Payment')], max_length=20, null=True)),
                ('related_entity_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
    ]
