# Generated by Django 5.1.7 on 2025-10-05 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professionals', '0001_initial'),
        ('quotes', '0001_initial'),
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requests.servicerequest'),
        ),
        migrations.AddField(
            model_name='quote',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professionals.professional'),
        ),
        migrations.AddField(
            model_name='quote',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requests.servicerequest'),
        ),
        migrations.AddField(
            model_name='booking',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.quote'),
        ),
        migrations.AddField(
            model_name='serviceissue',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.booking'),
        ),
    ]
