# Generated by Django 5.1.7 on 2025-11-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
